name: Build and Release

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-jvm:
    name: Build JVM Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '24'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon || true

      - name: Create distribution
        run: ./gradlew installDist --no-daemon

      - name: Upload JVM artifact
        uses: actions/upload-artifact@v4
        with:
          name: csak-jvm
          path: build/install/csak/
          retention-days: 7

  build-native:
    name: Build GraalVM Native Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM JDK 24
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build native image
        run: ./gradlew nativeCompile --no-daemon
        env:
          JAVA_OPTS: "-Xmx4g"

      - name: Test native binary
        run: |
          ./build/native/nativeCompile/csak --help
          ./build/native/nativeCompile/csak --version

      - name: Create tarball
        run: |
          cd build/native/nativeCompile
          tar -czf csak-linux-x64.tar.gz csak
          sha256sum csak-linux-x64.tar.gz > csak-linux-x64.tar.gz.sha256

      - name: Upload native binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: csak-native-linux-x64
          path: |
            build/native/nativeCompile/csak-linux-x64.tar.gz
            build/native/nativeCompile/csak-linux-x64.tar.gz.sha256
          retention-days: 30

  docker-jvm:
    name: Build JVM Docker Image
    runs-on: ubuntu-latest
    needs: build-jvm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build JVM Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.jvm
          push: false
          tags: csak:jvm
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-native:
    name: Build Native Docker Image
    runs-on: ubuntu-latest
    needs: build-native

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Native Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.native
          push: false
          tags: csak:native
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-jvm, build-native]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download native binary artifact
        uses: actions/download-artifact@v4
        with:
          name: csak-native-linux-x64
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/csak-linux-x64.tar.gz
            artifacts/csak-linux-x64.tar.gz.sha256
          body: |
            ## Cardano Swiss Army Knife (csak) ${{ github.ref_name }}

            ### Installation

            **Native Binary (Linux x64):**
            ```bash
            # Download and extract
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/csak-linux-x64.tar.gz
            tar -xzf csak-linux-x64.tar.gz
            chmod +x csak

            # Verify checksum
            sha256sum -c csak-linux-x64.tar.gz.sha256

            # Run
            ./csak --help
            ```

            **Docker (Build Locally):**
            ```bash
            # Clone repository
            git clone https://github.com/${{ github.repository }}.git
            cd cardano-swiss-army-knife

            # Build JVM Docker image
            docker build -f Dockerfile.jvm -t csak:jvm .

            # Build Native Docker image
            docker build -f Dockerfile.native -t csak:native .
            ```

            ### What's Changed
            - See commit history for details

            ### Checksums
            See `csak-linux-x64.tar.gz.sha256` for SHA-256 checksums.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
